CREATE TABLE IF NOT EXISTS Profiles (
Uuid TEXT NOT NULL UNIQUE,
DateTime INTEGER NOT NULL,
FirstName TEXT NOT NULL, 
CurrentName TEXT NOT NULL,
SkinUrl TEXT NOT NULL,
Skin TEXT NOT NULL,
SkinModel TEXT NOT NULL,
CapeUrl TEXT DEFAULT '',
Cape TEXT DEFAULT '',
Legacy INTEGER DEFAULT 0,
Demo INTEGER DEFAULT 0,
Comments TEXT DEFAULT '',
NameHistory INTEGER DEFAULT 0
);
